import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'intro',
        {
          type: 'category',
          label: 'Module 1: ROS 2 – The Robotic Nervous System',
          items: [
            'module1/chapter1_1_ros2_architecture',
            'module1/chapter1_2_ros2_nodes_topics',
            'module1/chapter1_3_services_actions',
            'module1/chapter1_4_robot_state_tf2',
            'module1/chapter1_5_launch_files',
            'module1/chapter1_6_testing_debugging'
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twins – Simulation Environments',
          items: [
            'module2/chapter2_1_simulation_environments',
            'module2/chapter2_2_robot_modeling_urdf'
          ],
        },
        {
          type: 'category',
          label: 'Module 3: AI Robot Brain – NVIDIA Isaac',
          items: [
            'module3/chapter3_1_introduction_isaac'
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Vision–Language–Action (VLA) Systems',
          items: [
            'module4/chapter4_1_introduction_multimodal'
          ],
        },
        {
          type: 'category',
          label: 'Module 5: Autonomous Humanoid System',
          items: [
            'module5/chapter5_1_autonomous_humanoid_system'
          ],
        }
      ],
    },
  ],
};

export default sidebars;
